//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRaVao
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DangKy()
        {
            this.VeRANgoais = new HashSet<VeRANgoai>();
        }
    
        public int id_DangKy { get; set; }
        public Nullable<int> id_DSDangKy { get; set; }
        public string id_TaiKhoan { get; set; }
        public Nullable<int> id_LoaiDangKy { get; set; }
        public string LyDo { get; set; }
        public string DiaDiem { get; set; }
        public System.DateTime ThoiGianDi { get; set; }
        public System.DateTime ThoiGianVe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DSDangKy DSDangKy { get; set; }
        public virtual LoaiDangKy LoaiDangKy { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeRANgoai> VeRANgoais { get; set; }
    }
}
