//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRaVao
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhSachDK
    {
        public int id_DangKy { get; set; }
        public string MaHV { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> id_DonVi { get; set; }
        public Nullable<int> id_ChuyenNganh { get; set; }
        public string TenDangKy { get; set; }
        public string LyDo { get; set; }
        public System.DateTime ThoiGianDi { get; set; }
        public System.DateTime ThoiGianVe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
