//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRaVao
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoHocVien
    {
        public string MaHV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TenCapBac { get; set; }
        public string TenChucVu { get; set; }
        public string TenDV { get; set; }
        public string TenChuyenNganh { get; set; }
        public byte[] Avatar { get; set; }
    }
}
