//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRaVao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoVe
    {
        public int id_SoVe { get; set; }
        public Nullable<int> SoVe1 { get; set; }
        public Nullable<int> id_DonVi { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DonVi DonVi { get; set; }
    }
}
