//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRaVao
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeRANgoai
    {
        public int id_VeRaNgoai { get; set; }
        public Nullable<int> id_DangKy { get; set; }
        public Nullable<System.DateTime> cDuyetDi { get; set; }
        public Nullable<System.DateTime> cDuyetVe { get; set; }
        public Nullable<System.DateTime> vbDuyetDi { get; set; }
        public Nullable<System.DateTime> vbDuyetVe { get; set; }
    
        public virtual DangKy DangKy { get; set; }
    }
}
