//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRaVao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public int id_ViPham { get; set; }
        public string id_HocVien { get; set; }
        public string id_NguoiGhi { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string ChiTietLoi { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
